[versions]
kotlin = "1.9.0"
dokka = "1.8.20"
compose = "1.4.3"
coroutines = "1.6.4"
koin = "3.4.3"
koin-compose = "1.0.4"
dependency-updates = "0.47.0"
kotlinter = "3.15.0"
serialization-json = "1.5.1"
android = "7.4.2"
android-core = "1.10.1"
android-lifecycle = "2.6.1"
android-activity-compose = "1.7.2"
android-navigation = "2.6.0"
android-test-core = "1.5.0"
android-test-runner = "1.5.2"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
dependency-updates = { id = "com.github.ben-manes.versions", version.ref = "dependency-updates" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
android-library = { id = "com.android.library", version.ref = "android" }
android-application = { id = "com.android.application", version.ref = "android" }

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-json" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
android-core = { module = "androidx.core:core-ktx", version.ref = "android-core" }
android-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "android-lifecycle" }
android-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "android-activity-compose" }
android-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "android-navigation" }
android-test-ui-manifest-compose = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
android-test-core = { module = "androidx.test:core", version.ref = "android-test-core" }
android-test-runner = { module = "androidx.test:runner", version.ref = "android-test-runner" }
